name: Deploy

on:
  push:
    branches: [ main ]

jobs:

  build:
    name: Deploy
    runs-on: self-hosted
    steps:

    - name: Who ami I
      run: whoami

    - name: Check out code
      uses: actions/checkout@v2

    - name: Python Dependencies
      run: /home/pi/venv/bin/pip install --no-input -r pi/requirements.txt

    - name: Install
      run: cp -r pi /home/pi
